### ISSUE TITLE
Quota blocks scaling to 5 build agents

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#1]
Just fixed some syntax errors in `quota.yaml` and after I enacted the quota the build agent can't scale past 1. 

Should either increase the quota or reduce the suggested number of replicas (I'm not sure the quota is actually necessary at all, though you could mention it as a possibility)

**Comment by viglesiasce** [comment]
No longer using quota in this tutorial.
