### ISSUE TITLE
jenkinsfile access another gke cluster for separating dev and production cluster.

### ISSUE THREAD

**Issue by g3gurung** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#104]
I am having a GKE cluster of (jenkins + dev), but I have a separate production GKE cluster so I don't know how to access and deploy(canary and production) from **jenkins cluster**(via jenkinsfile) to the **production cluster**.

```
echo 'accessing production project/cluster'
sh("gcloud container clusters get-credentials my_other_cluster --zone europe-west3-a --project my_other_project")
sh("kubectl get po")
sh("kubectl get svc")
```

I did the above in **jenkinsfile** but it is giving this error:
```
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get..."
```

**Comment by viglesiasce** [comment]
You need to ensure that the cluster that Jenkins runs in has the [scopes](https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam) enabled to allow it to get credentials.

**Comment by viglesiasce** [comment]
Closing as this is out of scope for the current tutorial. Will look to make an update in the future to include multiple clusters.
