### ISSUE TITLE
Update slave image to use Remoting 3.15 to mitigate Jenkins master incompatibility issue

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#109]
There is an issue where the gcr.io/cloud-solutions-images/jenkins-k8s-slave:v4 image won't properly connect to a Jenkins master running certain versions because of incompatibility between the master and the remoting client.

Issues:

https://issues.jenkins-ci.org/browse/JENKINS-48470

Jenkins [changelog](https://jenkins.io/changelog/) states:
* Restore binary compatibility with agents running Remoting versions older than 3.15 (regression in 2.98). (issue 48761, issue 48754, Retrospective thread in the developer mailing list)

In general I feel the image could be updated a bit more often, say once a month, to reduce the diff between the tool versions in the image and the real world (e.g. jenkins apis, gcloud, kubernetes).

Thanks!

**Comment by abobwhite** [comment]
I just ran into this trying to do `gcloud auth configure-docker`...I agree that updating more often should be necessary

**Comment by viglesiasce** [comment]
Updated the tutorial to use the upstream Jenkins Helm Chart which updates to the latest JNLP agent image.

#96
