### ISSUE TITLE
Change canary env RC to be called "canary" rather than "staging"

### ISSUE THREAD

**Issue by viglesiasce** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#11]

**Comment by eggie5** [comment]
👍

**Comment by eggie5** [comment]
Hi,

I just went through the tutorial and it worked great and was very informative. I was a little confused about deployment strategies w/ k8s but I'm have a more of a clear idea now. Seems like most of them require some type of CI/CD server to generate the k8s configs and building docker images or else your managing all that on your own. 

It was interesting using the canary deployment patter compared to the stag/prod pattern I'm used to. I'm completely fine with it, but the only problem I see is when you canary deploy has a DB migration/change. Then your canary and prod code will conflict. Any tips to deal w/ this?

**Comment by Chekote** [comment]
👍
