### ISSUE TITLE
jenkins-slave is offline

### ISSUE THREAD

**Issue by nickleefly** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#111]
jenkins-slave is offline (suspend) from jenkins webpage.

My environment:
I have jenkins running on a debian server, created a k8s cluster in gcp. installed kubernetes-plugin, configed k8s in jenkins cloud section,(using admin/k8s password.),

Then created a test pipeline job using the following script
```
podTemplate(label: 'pod-golang', 
    containers: [
        containerTemplate(
            name: 'golang',
            image: 'golang',
            ttyEnabled: true,
            command: 'cat'
        )
    ]
) {
    node ('pod-golang') {

        stage 'Switch to Utility Container'
        container('golang') {

          sh ("go version")

        }
    }
}
```
from `kubectl get pods` I can see the pod is created, but on jenkins webpage, jenkins-slave is alwasy showing offline
Any ideas

Thanks

**Comment by later123** [comment]
Hello nickleefly, 
Have you resolved this issue?
My Jenkins pipeline showing: 
_Still waiting to schedule task
jenkins-slave-5n7nd-0jj7b is offline._  
The pod is always restarting like below:
kubectl get -a pods --watch
NAME                         READY     STATUS    RESTARTS   AGE
jenkins-slave-gljw5-3r8s3   0/1       Pending   0         0s
jenkins-slave-gljw5-3r8s3   0/1       Pending   0         1s
jenkins-slave-gljw5-3r8s3   0/1       ContainerCreating   0         1s
jenkins-slave-gljw5-3r8s3   1/1       Running   0         2s
jenkins-slave-gljw5-3r8s3   0/1       Error     0         1m
jenkins-slave-gljw5-3r8s3   0/1       Terminating   0         1m
jenkins-slave-gljw5-3r8s3   0/1       Terminating   0         1m
jenkins-slave-gljw5-thkrp   0/1       Pending   0         0s
jenkins-slave-gljw5-thkrp   0/1       Pending   0         1s
jenkins-slave-gljw5-thkrp   0/1       ContainerCreating   0         1s
jenkins-slave-gljw5-thkrp   1/1       Running   0         3s

Do you have any idea?  Thanks in advance.

**Comment by altitdb** [comment]
@later123 I have the same problem. Do you fix it?

**Comment by andrimuhyidin** [comment]
Same problem with me... any idea?

**Comment by ksanchez15** [comment]
Having this issue here. running `kubectl get pods` returns the the state of the pod is 'pending'
