### ISSUE TITLE
Credentials selector doesn't work

### ISSUE THREAD

**Issue by concrete-ricardo-silva** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#117]
After create a credential, they don't appear in selector, just none appears to select.

**Comment by aplex** [comment]
I had the same problem, and found out that you need to create a cluster with special scopes/permissions for this to work. It is mentioned in the beginning of the article:

```
$ gcloud container clusters create jenkins-cd \
  --num-nodes 3 \
  --scopes "https://www.googleapis.com/auth/projecthosting,storage-rw"
```

 If you already have a cluster, you can re-create the node group with correct permissions following the guide from https://medium.com/google-cloud/updating-google-container-engine-vm-scopes-with-zero-downtime-50bff87e5f80

**Comment by viglesiasce** [comment]
Indeed the one that is particularly important in this case is `https://www.googleapis.com/auth/projecthosting`.
