### ISSUE TITLE
"Prerequisites" step's link to enable APIs doesn't enable the needed Container Build API

### ISSUE THREAD

**Issue by aleczadikian** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#125]
The "Prerequisites" step has a link "Enable the Google Compute Engine and Google Container Engine APIs" to enable APIs that takes me to a page saying "Register your application for Compute Engine API, Kubernetes Engine API in Google Cloud Platform." Odd that the Container Engine API isn't mentioned. But turns out we need the Container Build API; I don't know if that's the same as the Container Engine API:

In the step "Deploy a canary release to canary," after changing the version number, HTML, and project ID in the Jenkinsfile, we scan the branches and view the console output of the `canary` branch build in Jenkins. My console output is showing:

```
[sample-app_canary-xxxxxxx] Running shell script
+ PYTHONUNBUFFERED=1 gcloud container builds submit -t gcr.io/my-project-id/gceme:canary.2 .
Creating temporary tarball archive of 31 file(s) totalling 77.3 KiB before compression.
Uploading tarball of [.] to [gs://my-project-id_cloudbuild/source/xxxxxxx.tgz]
API [cloudbuild.googleapis.com] not enabled on project [xxxxxxxxx].
 Would you like to enable and retry (this will take a few minutes)? 
```
with a spinning wheel at the end. Probably waiting for a yes or no from stdin.

I went to https://console.cloud.google.com/gcr/builds and enabled the Cloud Build API. Waited 10 minutes, then retried the canary build in Jenkins, and it worked.

**Comment by viglesiasce** [comment]
Thanks for opening this issue and apologies!

This has been fixed with:
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/commit/c67a9f9ca7d6959118de3f1d25a273a6c045d493
