### ISSUE TITLE
This repository is out of sync with the tutorial posted on google cloud for Jenkins on Kubernetes

### ISSUE THREAD

**Issue by wshamim** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#126]
I was following the tutorial from here.
[https://cloud.google.com/solutions/jenkins-on-kubernetes-engine-tutorial](https://cloud.google.com/solutions/jenkins-on-kubernetes-engine-tutorial)

and I think the commit [Use official Helm chart to install Jenkins](https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/commit/e3d7184bc4d00062f7b1061e57fe0486d0e956ad) has removed some of the required files for that tutorial specially  `jenkins/k8s` directory.

Maybe someone needs to update the tutorial.

Also it would be nice if you add the `Configuring external load balancing` session in your Readme.md here on the github.

Peace.

**Comment by viglesiasce** [comment]
Hey @wshamim!

Thanks for opening this issue. The docs changes upstream are inflight. Apologies for the missed timing.

Will add some notes on exposing Jenkins publicly.

**Comment by viglesiasce** [comment]
All set!

https://cloud.google.com/solutions/jenkins-on-kubernetes-engine-tutorial
