### ISSUE TITLE
{env.BRANCH_NAME} is null

### ISSUE THREAD

**Issue by meteorlad** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#127]
```
def  imageTag = "gcr.io/${project}/${appName}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"
```

The  `${env.BRANCH_NAME}` is NULL?

**Comment by viglesiasce** [comment]
I was not able to reproduce. Can you check that you created the Jenkins job as a multibranch pipeline?

**Comment by meteorlad** [comment]
Ok, thank you. This problem has been solved
