### ISSUE TITLE
Create new users using Jenkins

### ISSUE THREAD

**Issue by halcolo** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#146]
I follow the tutorial to create my Jenkins Kubernetes pod with Helm but the option to manage users is missing, I need to manage the users that enter to the platform for control the security.
How can I install or configure Jenkins with the user manage, is possible from the yaml file?
Or what is an alternative option to create users and do not use the admin user?

Aditional Info:
jenkins-war:2.164.2
slave-installer:1.6

**Comment by viglesiasce** [comment]
Setting this up is out of scope for this particular tutorial but you can find more info here:
https://wiki.jenkins.io/display/JENKINS/Standard+Security+Setup

And in the values file here:
https://github.com/helm/charts/tree/master/stable/jenkins#adding-customized-securityrealm
