### ISSUE TITLE
"status": "Failure" after running the command "curl \ > http://localhost:8001/api/v1/namespaces/new-feature/services/gceme-frontend:80/proxy/version"

### ISSUE THREAD

**Issue by seanlubbers1** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#148]
Getting "status": "Failure" after running the command "curl \
> http://localhost:8001/api/v1/namespaces/new-feature/services/gceme-frontend:80/proxy/version". 

After creating the new-feature pipeline it is showing failed.

Here is the output:
{
 "kind": "Status",
 "apiVersion": "v1",
 "metadata": {
 },
 "status": "Failure",
 "message": "services \"gceme-frontend\" not found",
 "reason": "NotFound",
 "details": {
   "name": "gceme-frontend",
   "kind": "services"
 },

**Comment by viglesiasce** [comment]
I was not able to reproduce this. What was the rest of the build output?

**Comment by seanlubbers1** [comment]
This was from a while ago—I'll go ahead and close.
