### ISSUE TITLE
cd-jenkins service account doesn't have access to retrieve resources in production namespace

### ISSUE THREAD

**Issue by sammourad** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#151]
Thank you for the great tutorial.
I ran through the updates today and noticed this issue.
Should there be a step to grant cd-jenkins service account access to production namespace?
```
+ kubectl --namespace=production apply -f k8s/services/
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
Name: "gceme-backend", Namespace: "production"
Object: &{map["apiVersion":"v1" "kind":"Service" "metadata":map["name":"gceme-backend" "namespace":"production" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "spec":map["ports":[map["targetPort":'\u1f90' "name":"http" "port":'\u1f90' "protocol":"TCP"]] "selector":map["app":"gceme" "role":"backend"]]]}
from server for: "k8s/services/backend.yaml": services "gceme-backend" is forbidden: User "system:serviceaccount:default:cd-jenkins" cannot get resource "services" in API group "" in the namespace "production"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
Name: "gceme-frontend", Namespace: "production"
Object: &{map["metadata":map["name":"gceme-frontend" "namespace":"production" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "spec":map["ports":[map["name":"http" "port":'P' "protocol":"TCP" "targetPort":'P']] "selector":map["app":"gceme" "role":"frontend"] "type":"LoadBalancer"] "apiVersion":"v1" "kind":"Service"]}
from server for: "k8s/services/frontend.yaml": services "gceme-frontend" is forbidden: User "system:serviceaccount:default:cd-jenkins" cannot get resource "services" in API group "" in the namespace "production"
```

**Comment by sammourad** [comment]
p.s. my solution for this issue is to create a clusterrolebinding for the service account (cd-jenkins) to cluster-admin role. Sounds a little excessive though, but I'm not sure what the minimal role needed for this...

**Comment by sammourad** [comment]
p.s. #2: under this section "Phase 1: Add your service account credentials", I only see my project id displayed and not the two jenkins service accounts as shown in the screenshot.

**Comment by maheshgurav** [comment]
Hi @sammourad, I am facing the same issue, also I am not able to update clusterrolebinding, command says that, 
**Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "cluster-admin-binding" already exists**
Please let me know how did you created clusterrolebinding for service account (cd-jenkins)
Thanks in advance.

**Comment by maheshgurav** [comment]
Fixed issue, I got the command, thank you for your solution

**Comment by viglesiasce** [comment]
Fixed in f15bdaab5258f12e3665f5e560b2a2590f2c7c9b

Apologies for the issue.

**Comment by viglesiasce** [comment]
The minimal scope of the service account would depend on if you wanted to continue to have Jenkins be able to create the namespaces for the dev/new-feature branches. If not, you could have it be admin in only the namespaces that you pre-created.

**Comment by VGerris** [comment]
I needed to set the service account name too to jenkins-sa as mentioned here:
https://issues.jenkins-ci.org/browse/JENKINS-62646?focusedCommentId=394617&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-394617
to get it to work.
