### ISSUE TITLE
pod-name is not being fetched due to the label in kubectl get pods command

### ISSUE THREAD

**Issue by uptownaravi** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#153]
The section https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes#configure-and-install-jenkins

where point 4 says export POD_NAME the label says  -l "component=cd-jenkins-master"

but when we describe the pod we can see the label set as "app.kubernetes.io/component=jenkins-master"

should the command be changed to add -l "app.kubernetes.io/component=jenkins-master"

**Comment by viglesiasce** [comment]
Thank you for pointing this out!!

**Comment by viglesiasce** [comment]
Fixed here:
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/commit/46b1bd2982a7ffdc6c62a5d03968f15ddbd3f67d
