### ISSUE TITLE
Jenkins job fails due to frontend readiness probe fails

### ISSUE THREAD

**Issue by keisei803** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#154]
Jenkinsfile create deployment before service, but frontend readiness check require backend service first.
Jenkins job fails due to  frontend readiness/verifyDeployments fails.

https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/master/sample-app/Jenkinsfile#L103
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/master/sample-app/k8s/dev/frontend-dev.yaml#L41

**Comment by viglesiasce** [comment]
Thanks! Fixed in f414ee8c4f7d1d40a1b535390cb196c874f11c13
