### ISSUE TITLE
Extra credit: deploy a breaking change, then roll back

### ISSUE THREAD

**Issue by xero88** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#18]
Hi,

Great tutorial, thank you!
I'm wondering if you would detail more the step "Extra credit: deploy a breaking change, then roll back"

Thank you =)

**Comment by viglesiasce** [comment]
Try to deploy a change that breaks the application in some obvious way (text is not correct). Try to use the deployment rollback functionality in order to quickly get back to a known good state.
