### ISSUE TITLE
There appears to be no way to secure against http:// calls with L7

### ISSUE THREAD

**Issue by jnorment-q2** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#20]
... so no way to deploy a production (secure) web service (in this case CI) using L7?

Is that a known limitation of L7?

**Comment by viglesiasce** [comment]
There is a way. It requires that you block them completely though, currently a redirect is not available. 

https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#blocking-http

**Comment by jnorment-q2** [comment]
I fail at reading.

Thank you *so much* for taking the time to point this out!!!
