### ISSUE TITLE
Multiple namespaces

### ISSUE THREAD

**Issue by skylve** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#22]
In the readme :

`You'll have two primary environments - staging and production - and use Kubernetes namespaces to isolate them.`

But no reference of `staging` namespace (only `production`).
I see the labels used are differents, but shouldn't the readme be worded differently then ?

**Comment by viglesiasce** [comment]
Hey @skylve! Great point. That is vestigial from a previous iteration of the tutorial that did not deploy as a canary. Thanks for pointing it out. 

How did the rest of the tutorial treat you?

**Comment by viglesiasce** [comment]
Fixed now.
