### ISSUE TITLE
Environments and branches confusions

### ISSUE THREAD

**Issue by pdoreau** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#24]
Hello. Great guide ! However there are some points not clear to me :

- "roll it out to the rest of your users by creating a branch called production  and pushing it to the Git server:". The Git 3 commands after that don't show anything about a branch called production.
- what is the exact purpose of the master branch ? On the first hand, it seems to be the way to deploy 4/5 pods in production, and on the other hand it seems to be more related to staging : "Once you are done, merge your branch back into master to deploy that code to the staging environment:...git push orign master"
- in the picture, there is a stage called "Deploy Application to production namespace". However, I can't see any stage in the Jenkinsfile with that name (even created dynamically).

**Comment by viglesiasce** [comment]
Sorry for the confusion here, the master branch is for production.
