### ISSUE TITLE
Slave Image

### ISSUE THREAD

**Issue by dknaack** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#26]
I cant find the reference to the slave image. 
I would like to extend it. 

How can i dot this?

**Comment by viglesiasce** [comment]
Have a look here:
https://cloud.google.com/solutions/jenkins-on-container-engine#customizing_the_docker_image

**Comment by dknaack** [comment]
What i was looking for could be found in the jenkins configuration at http://*/configure under Pod Template (or in the config.xml)

No, i can build my own slave image and let jenkins use it. 

Thanks!
