### ISSUE TITLE
Removing Unused Replica Sets After Deply

### ISSUE THREAD

**Issue by Knaackee** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#29]
Ive noticed that after a deploy, the old replica set is still present.
How to auto remove the old replica set (Desired 0) after deploy?

**Comment by viglesiasce** [comment]
I don't believe it is possible to remove the replicasets automatically. It will be automatically scaled down for you already however.

**Comment by eggie5** [comment]
Yes, this isn't anything to do in particular w/ this project. It's connected to K8s `Deployments`. I noticed too, that when running `apply` on a `Deployment` that it leaves "orphaned" replica sets that are "turned off". Harmless, I suppose, but distracting to say the least...

**Comment by cmosgh** [comment]
Won't those replica sets fill up the disk/memory of the cluster?
I am just worried of having to manually take care of them since a CI workflow is creating them on each build on our cluster

**Comment by viglesiasce** [comment]
In the deployment spec you can [define the revisionHistoryLimit](https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_deploymentspec)

**Comment by viglesiasce** [comment]
Also to @cmosgh those replicasets are scaled down to 0 regardless so are not taking up any cluster resources.

**Comment by philpoore** [comment]
@viglesiasce According to docs that is incorrect.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit
> All old ReplicaSets will be kept by default, consuming resources in etcd and crowding the output of kubectl get rs

**Comment by Balukeethu** [comment]
Is there any way to set revisionHistoryLimit into namespace or node level ?
