### ISSUE TITLE
Loadbalancer is never able to connect service

### ISSUE THREAD

**Issue by usopan** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#31]
kubectl describe ingress jenkins --namespace jenkins

always returns unhealthy backend status.
All pods are running when I check jenkins namespace

**Comment by viglesiasce** [comment]
The loadbalancer configuration and health checking can take up to 5-7 minutes. Did you wait that long?

Were you able to reach the NodePort of the service directly? What version of K8s?

**Comment by usopan** [comment]
Yes it worked after waiting long enough.
