### ISSUE TITLE
Provide image build instructions

### ISSUE THREAD

**Issue by Temikus** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#32]
Thanks for publishing this!

One note though, is it possible to publish the image build instructions or, at least, the build script/rules for the image? At least when I tried it last, there was a considerable amount of prep work involved in getting a good Jenkins image running in a container: latest public Docker images are really buggy, building a container yourself requires much wrangling with java images, there are `jenkins_home` issues if one initialises it at the top of the filesystem, etc.

Otherwise this step has quite a bit of magic to it:

```
gcloud compute images create jenkins-home-image --source-uri https://storage.googleapis.com/solutions-public-assets/jenkins-cd/jenkins-home-v2.tar.gz
```

I think providing some idea in how to prepare an image yourself will actually make it more of a solution, than a demo.

P.S. I do admit I may be missing something - so if there is a link for the image prep - just let me know and I'll patch the docs.

**Comment by viglesiasce** [comment]
Hey @Temikus !!

Thanks for the feedback!

I have actually been working on exactly this over in the kubernetes/charts repo. Check out this pull request:
https://github.com/kubernetes/charts/pull/61

I attempt to take the covers off the configuration that comes in the home volume. You will see the config.xml as well as how plugins are installed (in the Dockerfile). 

For more info check out:
https://cloud.google.com/solutions/jenkins-on-container-engine

**Comment by Temikus** [comment]
@viglesiasce Awesome, that is exactly what I was looking for. Glad to see there's work being done on it, thanks!
