### ISSUE TITLE
Jenkins Slave Connecting to Cloud SQL

### ISSUE THREAD

**Issue by dknaack** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#33]
Hello,

i would like to connect to my cloud sql instance in order to perform database migrations as part of my build process.

At the moment i get a time out so i tried to allow access to the cloud sql instance for the jenkins master ip address. This does not work. After i tried to allow access to any ip address "0.0.0.0/0" and this works.

I obviously don't want to allow access to any ip.

Any ideas on how to solve my problem?

**Comment by viglesiasce** [comment]
Hey @dknaack 

When creating the cluster you need to authorize it for the cloud-sql scope. Did you do that?

**Comment by dknaack** [comment]
Hey! Thanks.

No i didn't. How to do that? 
Do you have a link or something? 

Thanks!

**Comment by viglesiasce** [comment]
@dknaack Check out the scopes section here:
https://cloud.google.com/sdk/gcloud/reference/container/clusters/create

it should be something like:

gcloud container clusters create my-cluster --scopes sql

**Comment by gobigdave** [comment]
I have both the sql and the sql-admin scope turned on, and I still can't get my tests to access the database. I'm trying a cloudsql proxy now, but it won't even connect to that.
