### ISSUE TITLE
Only one slave executor is created.

### ISSUE THREAD

**Issue by TomDeVito** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#35]
When I have multiple jobs in the build queue only one slave executor is created and only one job is processed.  In the settings I have the cap set to 10 but only one is ever created.  Any idea what I am doing wrong or a way to get more slave executors to run?

**Comment by viglesiasce** [comment]
Hey @TomDeVito!

In the job conifg you will need to tick the flag for "Execute concurrent builds if necessary"

**Comment by TomDeVito** [comment]
@viglesiasce Even if these are different type of jobs?

**Comment by viglesiasce** [comment]
Sorry I was thinking for the same job. I haven't seen this issue with only 1 executor being created at a time. Were you able to figure this out?

**Comment by viglesiasce** [comment]
Hey @TomDeVito!

I was able to reproduce this finally. The way to work around it is to add the following environment variable to the Jenkins deployment:

```
- name: JAVA_OPTS
  value: -Dhudson.model.LoadStatistics.decay=0.1 -Dhudson.model.LoadStatistics.clock=3000
```
