### ISSUE TITLE
Default Jenkins resources to low

### ISSUE THREAD

**Issue by panzerdev** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#48]
When I created the `Deployment` and tried to get to the settings page of Jenkins the instance always crashed. After a bit of investigation I found the resource definition in the `Deployment` to no be enough

``` resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 1000Mi
```

I changed it to work fine

``` resources:
          requests:
            cpu: 500m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 6000Mi
```

Does the original 1Gb RAM limit work for anybody?

[Jenkins Deployment](https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/master/jenkins/k8s/jenkins.yaml)

**Comment by viglesiasce** [comment]
Its worked for me without changes and I believe is a safe default. Was there a specific error in the Jenkins logs?

**Comment by panzerdev** [comment]
There was no error in the logs I could see only the pod crashed and started again. Increasing the RAM solved it for me.

**Comment by p1hr** [comment]
1Gb did not work for me, container crashed with OOM during start until I increased memory resources

**Comment by TomDeVito** [comment]
Was having the same issue, had to increase the resources as well.

**Comment by viglesiasce** [comment]
Bumped up by 500Mi. 

edf425163c639ef177ead1cf808bfab46e0b64ee

**Comment by severinraez** [comment]
Whenever I try to open the Jenkins configuration UI, the pod crashes.

        resources:
          limits:
            cpu: 1000m
            memory: 3000Mi
          requests:
            cpu: 1000m
            memory: 3000Mi

Works for me.

Could be out of scope for this project, I only do this because I use this setup as a base to engineer a more complex pipeline.

**Comment by eth001** [comment]
Hello everyone
where and how can I change that value ? I am stuck with it, jenkins' worker have always and only 1GB, which is not enough for my build and always fail for insufficient memory.
