### ISSUE TITLE
Ingress: Instance may belong to at most one load-balanced instance group

### ISSUE THREAD

**Issue by dghubble** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#49]
Going through this on a GKE cluster which has an existing HTTPS load balancer (manually setup), I find that Ingress cannot create a new instance group over the cluster instances.

```
kubectl apply -f jenkins/k8s/lb
kubectl describe ingress -n=jenkins
Name:                   jenkins
Namespace:              jenkins
Address:
Default backend:        jenkins-ui:8080 (10.12.1.26:8080)
TLS:
  tls terminates 
Rules:
  Host  Path    Backends
  ----  ----    --------
  *     *       jenkins-ui:8080 (10.12.1.26:8080)
Annotations:
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason  Message
  ---------     --------        -----   ----                            -------------   --------        ------  -------
  32m           32m             1       {loadbalancer-controller }                      Normal          ADD     jenkins/jenkins
  32m           27s             36      {loadbalancer-controller }                      Warning         GCE     [googleapi: Error 400: Validation failed for instance 'projects/myproejct...': instance may belong to at most one load-balanced instance group., instanceInMultipleLoadBalancedIgs]
```

Typically, I've setup up the Load Balancers on Google Cloud manually and used a single load balancer targeting the instance group, with a backend service for each Kubernetes service. The Google LoadBalancer Controller for Ingress seems to make a fresh instance group for each ingress resource, which causes a validation error for Google Cloud?

Anyone else seeing this? Thanks folks.

**Comment by dghubble** [comment]
All I've dug up is thread in Slack archives where @IanLewis mentions running into this issue. http://kubernetes.slackarchive.io/google-containers/-/1444311803/1444719778/1444318620000066/

**Comment by IanLewis** [comment]
Yah, this is a problem inherent with how Ingress controller on GCP works. A new instance group is created to mitigate impact on the cluster if something goes wrong with the Ingress controller, but it also means that you can't combine Ingress and non-Ingress HTTP load balancers. The only workaround I can think of is to just use NodePort and create all of your load balancers manually.

**Comment by dghubble** [comment]
Thanks, this issue doesn't seem like something continuous-deployment-on-kubernetes can fix so I'll close. I ended up manually setting up a GCP load balancer and trying that out.

**Comment by clusc** [comment]
We're running into this issue as well. Would it be possible to limit the instances that will be added to the instance group(i.e. only instances in a node-pool that shall be added)?
