### ISSUE TITLE
Question: How to use Github for source but GCR for images?

### ISSUE THREAD

**Issue by Chekote** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#50]
Thanks so much for a great tutorial, it was extremely helpful in getting an understanding of k8s on GCE. Everything worked great when following the tutorial exactly, but I'm running into some issues when making variations to fit my own particular project environment.

I'm currently working with only the very beginning of the project, in that I'm grabbing the source code from SCM, building an image, and trying to push it to GCR. I'm using Github for SCM and not Google, and I've got that working great:

<img width="901" alt="screenshot 2016-11-02 15 51 26" src="https://cloud.githubusercontent.com/assets/550486/19947147/cadc1f0a-a114-11e6-8a36-a8f11836f77d.png">

But the problem arises when I try to push my image to GCR. I have the credentials configured in the Jenkins Credentials area:

<img width="908" alt="screenshot 2016-11-02 15 56 21" src="https://cloud.githubusercontent.com/assets/550486/19947181/efb54112-a114-11e6-92c7-af52a1c374a9.png">

But because I am not using Google for SCM, the Google API credentials are not referenced in the projects configuration. I am assuming that the `gcloud docker push` commands work in this tutorial only because the prior `checkout scm` command happened to authenticate with the credentials, which allows the `gcloud docker push` to piggy back on the pre-existing authentication.

My question is, if I'm not using Google SCM, and therefore not authenticating with the Google API credentials at the point that I pull the source from SCM. How do I get Jenkins to authenticate before trying to do `gcloud docker push`?

**Comment by viglesiasce** [comment]
You should be able to do the push as along as your cluster has the `storage-rw` scope. Is there an error in the build output?

**Comment by Chekote** [comment]
The initial error I got was:

`denied: Unable to create the repository, please check that you have access to do so.`

So I was wondering if having an existing repo for the image would help. I manually built and pushed the image from my workstation, and after doing so, the message from the Jenkins build just became more vague:

`denied: Access denied.`

I used the exact same credentials on my workstation to perform the initial push, so I'm assuming that means that the `storage-rw` scope is in place.

It just seems that the Jenkins server is not using the credentials in my pipeline. I'm assuming that adding the credentials to Jenkins global credentials is not enough for the Jenkins job to use it. I need to somehow configure the build to do so (just as you do when selecting the credentials for the SCM).

**Comment by viglesiasce** [comment]
You can check the scopes available to the cluster by running:

`gcloud --format yaml container clusters list`

**Comment by Chekote** [comment]
I don't see any mention of `storage-rw` scope when I do that. The only mentions of scope are two instances of:

```
  oauthScopes:
  - https://www.googleapis.com/auth/compute
  - https://www.googleapis.com/auth/devstorage.read_only
  - https://www.googleapis.com/auth/service.management.readonly
  - https://www.googleapis.com/auth/servicecontrol
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
```

So I'm guessing I screwed up something along the way? If so, can you point me at the part of the tutorial that I most likely messed up at?

Sorry for the cluelessness, I'm just trying to get the hang of this >.<

**Comment by viglesiasce** [comment]
Check out the params in the create cluster command:
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes#create-a-kubernetes-cluster

You have been kicking ass!!! Thanks so much for all the updates and feedback.

**Comment by Chekote** [comment]
Thanks! ^_^ I'm trying XD

That makes perfect sense now. It's been a while since I created the cluster, but I think I may have created it via the web console, which would explain the missing scopes. I looked up [clusters update](https://cloud.google.com/sdk/gcloud/reference/container/clusters/update), but there doesn't seem to be a way to change the scopes after the fact. I'm really hoping I don't have to nuke and re-create the cluster.

Are you aware of any way to change the scopes on an existing cluster?

**Comment by Chekote** [comment]
There doesn't seem to be a way to edit the permissions in the web interface either. :(

I can view them just fine, but there's not edit option.

<img width="463" alt="screenshot 2016-11-02 18 26 41" src="https://cloud.githubusercontent.com/assets/550486/19951132/f9ab22d0-a129-11e6-94a5-a2a6e26e7519.png">

**Comment by Chekote** [comment]
Well poo. This makes me sad: http://blogs.candoerz.com/question/120698/changing-permissions-of-google-container-engine-cluster.aspx
