### ISSUE TITLE
Login credentials not added to the container

### ISSUE THREAD

**Issue by danielckv** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#58]
I'm dealing with an issue that I can't login to admin's account on Jenkins after setting up the envirment with the options secret file as seen in the README.md file.

Tried to update the login details again in the cloud but again - no luck.

**Comment by rjjatson** [comment]
@danielckv hi daniel, what did you do to solve this issue?

**Comment by danielckv** [comment]
@rjjatson it's the admin username

**Comment by rjjatson** [comment]
yep, just found it too, thanks.
