### ISSUE TITLE
Mount volume to docker image in pipeline won't work

### ISSUE THREAD

**Issue by Kliton** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#59]
Hi, i'm having an issue when i try to add a host dir as volume to a docker image.

When i try to run the same code locally on OsX all works fine.

Here is the test script that i'm running on jenkins ( on GCE, kubernetes )

```groovy
node {
    checkout scm

   stage 'test'
    sh('cd /var && mkdir reactcompiler')
    sh('docker run -v /var/reactcompiler:/app/src/public -t reactcompiler:1.0.0 "cd /app/src/public && touch b.txt"')
    sh("cd /var/reactcompiler && ls")

}

**Comment by viglesiasce** [comment]
This is because the docker volumes are being mounted from the underlying kubernetes node not the Jenkins agent.

**Comment by Kliton** [comment]
And how i can solve this thing?

**Comment by Kliton** [comment]
I solved. Thank you.
