### ISSUE TITLE
Provide information on utilizing restore.tgz / GCS_RESTORE_URL

### ISSUE THREAD

**Issue by brianredbeard** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#6]
Looking in the replication controller definition I find reference to the variable `GCS_RESTORE_URL`. Digging further into the `start.sh` script reveals that the script will attempt to pull down a "backup" from GCS and prime jenkins with this information.

Looking back through the RC I don't see a pod with the capability of performing the backup operation nor any documentation about how to perform the initial setup of the container.  I would _assume_ this means a user should stand up jenkins on their own and tar up `JENKINS_HOME` and place it on GCS noting the URL.

Finally, when looking through the container further I find that there is a rather old version of Jenkins:

```
root@45885ae19873:/usr/share/jenkins# java -jar jenkins.war --version
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
1.609.2
```

I understand that this is the LTS release of Jenkins, but even still it's (as of this issue being filed) 234 days old with 7 LTS releases since then 3 batches of security advisories:

https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-02-24
https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-12-09
https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-11-11

**Comment by viglesiasce** [comment]
Hey there @brianredbeard!!
Sorry for the delayed response. The backup/restore steps can be found [here](https://cloud.google.com/solutions/automated-build-images-with-jenkins-kubernetes#jenkins_backup_and_restore).

I have taken a pass at updating this for using the latest version of Jenkins and utilizing some of the Kubernetes 1.2 features over in this branch:
https://github.com/viglesiasce/continuous-deployment-on-kubernetes/tree/1.2-update

It's still a WIP but should be merged in by the end of the week. Feel free to provide feedback here:
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/pull/8

**Comment by viglesiasce** [comment]
Closing as 1.2 update has been merged and no longer leverages the previous backup/restore steps. Link to more info on that backup/restore methodology is here:
https://cloud.google.com/solutions/automated-build-images-with-jenkins-kubernetes#jenkins_backup_and_restore
