### ISSUE TITLE
Waiting for next available executor

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#60]
Jenkins isn't able to find an executor.

**Comment by viglesiasce** [comment]
Sorry for the issues! I had fixed this on Friday but forgot to push the fix.

**Comment by viglesiasce** [comment]
If you'd like to fix your current install:

1. Update all of the plugins
1. Change the name of the container from "default" to "jnlp" in the "Manage System" config.

**Comment by clanstyles** [comment]
Worked, thank you. 

container from default to jnlp was the real fix.
