### ISSUE TITLE
Google Container permissions are randomly revoked.

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#62]
I've been using this in my dev environment and the permissions from the node pool are randomly being removed. This ends up causing a 503 error. How do I go about reporting or identifying why their being revoked/reset/removed? 

I can't actually change the permissions once it's live, so I know it's on Google's end. It was working.

**Comment by viglesiasce** [comment]
Can you post a log? What permissions do you think are being revoked? What API are you calling?

**Comment by clanstyles** [comment]
A log of what? Jenkins communicating to Docker throws a 503. I can't get any more information than that. It seems to have removed the permissions that gives it access to communicate to it. I've verified it with the Node Pool permissions. I though I was crazy, but it's happened many times now on my account. I've tried to contact Google about it via their bug tracker, and nodoby can reproduce it. I can't reproduce it, but it happens on my account like clock work.

**Comment by viglesiasce** [comment]
A log of anything that you have to help me help you with your issue. 

Jenkins doesn't communicate with Docker. Jenkins communicates with the Kubernetes plugin which in turn launches executors as pods in Kubernetes. The default executor config bind mounts the Docker binary and socket from the underlying hosts.

What is your build doing? What version of Kubernetes, Jenkins, and the Kubernetes Plugin?

**Comment by clanstyles** [comment]
It took a minute to remember what was going on. Jenkins was trying to pull from the source code which caused a 503. When you launch a Container Cluster with the permissions, per your article, if you check Node Pool permissions within Google Cloud it will actually show that the Node Pool has permission to access it. My node pool was having it revoked, randomly. I couldn't control when or how it was happening. The first time, it happened in 24 hours, the second and third time it took a few days.

**Comment by viglesiasce** [comment]
Ah so unrelated to Docker.

You were trying to clone something from Cloud Source Repositories and maybe metadata was short circuited for some reason it couldn't get credentials. I havent heard any reports of this but will keep an eye out and post back with any info I can find.

**Comment by clanstyles** [comment]
It pulled from Cloud Source and Google threw  a 503. I found it odd that it was a 503. I've reformatted the Jenkins cluster so many times, I'm not sure if I have logs.

If I PM you my user account, is there anyway to see activity on your end at Google that would see when / why that happened?

**Comment by clanstyles** [comment]
Welp! I have additional data on what's happening. I can push containers through my original 4 nodes I created too. If you add additional node pools via Google Cloud UI, they wont have access and your machines get "Access Denied". I'm assuming I have to create the additional node pool via the command line? 

This is unrelated but an additional permissions thing.

**Comment by viglesiasce** [comment]
Yep that sounds just right! Each node pool is configured independently so you would need to add the same scopes. Thanks for getting back to me @clanstyles!

**Comment by clanstyles** [comment]
I added a new node pool by doing

```
gcloud container node-pools create POOL-NAME --cluster=CLUSTER-NAME --machine-type=n1-standard-8 --scopes="https://www.googleapis.com/auth/projecthosting,storage-rw" --num-nodes=2 --disk-size=150 --image-type=gci
```
