### ISSUE TITLE
delete feature branch namespace

### ISSUE THREAD

**Issue by pierreozoux** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#63]
Thanks for the good work, I had a bit of issues with #32 but, I managed to find my way, and it helped a lot to bootstrap.

This question is more related to Jenkins, but if by any chance, somebody has the question?

With this deploy, we deploy each new feature branch automatically, this is great :) But how to detect that a branch has been deleted, and delete the associated namespace?

Thanks!

**Comment by viglesiasce** [comment]
I have been having developers delete their namespaces after they merge the branch but that is unreliable. This would likely have to be implemented as part of the MultiBranch plugin to enable a branch delete "hook" of sorts.

Another option is to create a periodic cleanup job that checks for namespaces without a matching branch, then deletes them.

**Comment by pierreozoux** [comment]
Yes good idea, there is this open actually, in the mean time, I'll use a periodic cleanup job.

thanks!
