### ISSUE TITLE
Is it possible to update Google Storage credentials without cloning the cluster?

### ISSUE THREAD

**Issue by danielckv** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#64]
I've forgot to enable the permission to write in storage of the instances in my Kubernetes cluster on GKE. Because of that I can't push docker images to my Google Registry after building the image.

Is there any optional ways to fix this or I need to do everything again with new cluster that enabled with this feature?

**Comment by philippefuentes** [comment]
I had the same problem cause I wanted to install jenkins on an existing cluster.
Found this post that allowed me to keep my cluster by redefining my node pools, since you can set the permissions at node pools level.

http://stackoverflow.com/a/40136339/3378958

hope this helps

**Comment by danielckv** [comment]
@philippefuentes thanks! works great!
