### ISSUE TITLE
Add more language features (Node, Go, etc).

### ISSUE THREAD

**Issue by paralin** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#66]
Making the image heavier is actually not that bad of a cost for faster builds and less bandwidth usage, assuming your Kubernetes nodes keep the image around when Jenkins workers are not in use (they should).

https://github.com/FuseRobotics/continuous-deployment-on-kubernetes/commits/master

I've iterated a bit on this repo here and added Node, Go, and a few other language support. Might be worth looking into merging a couple little pieces of that back here.

**Comment by rosera** [comment]
I just used this example to build a Maven pipeline, it has saved me a massive amount of time.

**Comment by viglesiasce** [comment]
This can be achieved by using your own image. Use the following pipeline as an example:

```
podTemplate(label: 'ubuntu-k8s', containers: [
    containerTemplate(name: 'ubuntu', image: 'ubuntu:16.04', ttyEnabled: true, 
        command: 'cat')    
  ]) {
    node('ubuntu-k8s') {
        container('ubuntu') {
            stage('Run Command') {
                sh 'cat /etc/issue'
            }
        }
    }
}
```
