### ISSUE TITLE
[question] could I run this locally on minikube?

### ISSUE THREAD

**Issue by rohit-ravikoti** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#67]
Hi,
I've been trying to get jenkins setup on a local machine with no success. I came across minikube and thought it might solve my problem. 

If anyone has an idea on how I could go about doing this, I would really appreciate it!

**Comment by viglesiasce** [comment]
In minikube I would use [helm](https://github.com/kubernetes/helm/blob/master/docs/quickstart.md) to install jenkins:

helm install stable/jenkins

**Comment by rohit-ravikoti** [comment]
@viglesiasce is that stable/jenkins  already configured for deploying to kubernetes like this project is?

**Comment by viglesiasce** [comment]
@rohit-ravikoti yes
