### ISSUE TITLE
Pod crashing on startup

### ISSUE THREAD

**Issue by nedkoh** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#69]
While following the steps outlined in the readme (and included in https://cloud.google.com/solutions/jenkins-on-container-engine-tutorial ) I'm getting the following error starting up Jenkins which points to possible issues with missing a shebang and starting up with dash shell instead of bash.
nedkoh@jenkins-160516:~/continuous-deployment-on-kubernetes$ kubectl get pods --namespace jenkins
NAME                      READY     STATUS             RESTARTS   AGE
jenkins-167554897-lf1lc   0/1       CrashLoopBackOff   13         47m
nedkoh@jenkins-160516:~/continuous-deployment-on-kubernetes$ kubectl logs jenkins-167554897-lf1lc --namespace jenkins
/usr/local/bin/jenkins.sh: eval: line 10: syntax error near unexpected token `('

**Comment by nedkoh** [comment]
Hi,
I have successfully troubleshooted and resolved the issue. Below are the findings:
1. the jenkins:2.7.2 image is good and jenkins.sh has the correct bash shebang
2. the above mentioned image fails on execution on line 10 where the startup arguments are accepted
3. we pass user information generated in the file (as per below) in the instructions
nedkoh@jenkins-160800:~/continuous-deployment-on-kubernetes$ tail jenkins/k8s/options
--argumentsRealm.passwd.jenkins=nji9NJI( --argumentsRealm.roles.jenkins=admin
4. as you see in the above the parameters are unescaped which causes any special characters to be interpreted (in this case the character is "(".
Conclusion:
Either escape the characters in the password value or mention in the instructions what are allowed values.

**Comment by viglesiasce** [comment]
Thanks for posting back @nedkoh !

**Comment by nedkoh** [comment]
This was a great start! I was able to customize and fine-tune the implementation to configure itself from scratch every time (not reliant on existing persistent volume) and scan all branches of all projects on GitHub (through the GitHub organization plugin) and fire up slaves with the Jenkins pipeline to build docker images.
