### ISSUE TITLE
Support for 1.2 deployment objects

### ISSUE THREAD

**Issue by devth** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#7]
`rollingupdate` doesn't work with multi-container replication controllers. How could this work with the new K8S 1.2 deployment objects? `kubectl edit deployment/...` doesn't lend itself very well to automation.

**Comment by viglesiasce** [comment]
Hey @devth!!!
I have taken a pass at updating this for using the latest version of Jenkins and utilizing some of the Kubernetes 1.2 features over in this branch:
https://github.com/viglesiasce/continuous-deployment-on-kubernetes/tree/1.2-update

It's still a WIP but should be merged in by the end of the week. Feel free to provide feedback here:
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/pull/8

**Comment by devth** [comment]
Thanks @viglesiasce! Great stuff :+1:  I'm working through it today. I'll close this since it's already tracked by #8.
