### ISSUE TITLE
Tutorial broken

### ISSUE THREAD

**Issue by khwerhahn** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#73]
Hi,

I think the tutorial needs to be fixed. 

1. the builds fail due to a docker error: 
![screen shot 2017-04-04 at 19 42 57](https://cloud.githubusercontent.com/assets/3821617/24670610/03c9428e-196f-11e7-8320-22d929a4c23f.png)

2. Swap Space note:
![screen shot 2017-04-04 at 19 46 38](https://cloud.githubusercontent.com/assets/3821617/24670715/724fed16-196f-11e7-879d-8b7fc5b92628.png)

3. I don't know if it is just me or the step with the git repo is also false. the /r/default doesn't work. I had to create manuall a /gceme repo and use that.

Hope you guys can help to fix it fast, so that I can play around with the working tutorial. Thx!

**Comment by viglesiasce** [comment]
1) The pod template should contain a host mount of the docker binary, do you see that?
2) There is no swap in GKE
3) The tutorial was updated to create it in #47

**Comment by viglesiasce** [comment]
@khwerhahn any update?

**Comment by khwerhahn** [comment]
Sorry not yet. Haven't gotten back to it yet.

**Comment by viglesiasce** [comment]
Please re-open if you continue to have issues as the fix was in #47
