### ISSUE TITLE
Private Repo - how to add alternative keys

### ISSUE THREAD

**Issue by rosera** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#74]
I am using a private REPO on GitHub and cant figure out how to add my ssh keys. I assumed they would be picked up via the .ssh directory, but this does not seem to be the case. I have seen some feedback regarding this and it appears, the jenkins user needs to be updated to include the private keys?

Does anyone know how to achieve this, with this tutorial?

**Comment by viglesiasce** [comment]
Configure your credentials then set them using the drop down in the source config:
https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin

**Comment by rosera** [comment]
FYI - if anyone wants to do this you should look at using Deploy Keys for SSH access as this gives you granular access over your various repositories.
[GitHub Deploy Keys](https://gist.github.com/zhujunsan/a0becf82ade50ed06115).

The credentials plugin requires you to successfully config your keys prior to being able to use. Ideally you should test this access via a command line to ensure it is working correctly prior to entering into the Jenkins plugin.
