### ISSUE TITLE
jenkins docker not found

### ISSUE THREAD

**Issue by khwerhahn** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#77]
Hi,

for some reason jenkins does't want to run the docker commands 

```
node {
  def project = 'REPLACE_WITH_YOUR_PROJECT_ID'
  def appName = 'gceme'
  def feSvcName = "${appName}-frontend"
  def imageTag = "gcr.io/${project}/${appName}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"

  checkout scm

  stage 'Build image'
  sh("docker build -t ${imageTag} .")

  stage 'Run Go tests'
  sh("docker run ${imageTag} go test")

  stage 'Push image to registry'
  sh("gcloud docker push ${imageTag}")

  stage "Deploy Application"
  switch (env.BRANCH_NAME) {
    // Roll out to canary environment
    case "canary":
        // Change deployed image in canary to the one we just built
        sh("sed -i.bak 's#gcr.io/cloud-solutions-images/gceme:1.0.0#${imageTag}#' ./k8s/canary/*.yaml")
        sh("kubectl --namespace=production apply -f k8s/services/")
        sh("kubectl --namespace=production apply -f k8s/canary/")
        sh("echo http://`kubectl --namespace=production get service/${feSvcName} --output=json | jq -r '.status.loadBalancer.ingress[0].ip'` > ${feSvcName}")
        break

    // Roll out to production
    case "master":
        // Change deployed image in canary to the one we just built
        sh("sed -i.bak 's#gcr.io/cloud-solutions-images/gceme:1.0.0#${imageTag}#' ./k8s/production/*.yaml")
        sh("kubectl --namespace=production apply -f k8s/services/")
        sh("kubectl --namespace=production apply -f k8s/production/")
        sh("echo http://`kubectl --namespace=production get service/${feSvcName} --output=json | jq -r '.status.loadBalancer.ingress[0].ip'` > ${feSvcName}")
        break

    // Roll out a dev environment
    default:
        // Create namespace if it doesn't exist
        sh("kubectl get ns ${env.BRANCH_NAME} || kubectl create ns ${env.BRANCH_NAME}")
        // Don't use public load balancing for development branches
        sh("sed -i.bak 's#LoadBalancer#ClusterIP#' ./k8s/services/frontend.yaml")
        sh("sed -i.bak 's#gcr.io/cloud-solutions-images/gceme:1.0.0#${imageTag}#' ./k8s/dev/*.yaml")
        sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s/services/")
        sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s/dev/")
        echo 'To access your environment run `kubectl proxy`'
        echo "Then access your service via http://localhost:8001/api/v1/proxy/namespaces/${env.BRANCH_NAME}/services/${feSvcName}:80/"
  }
}
```
Output Jenkins `docker not found`:
```
[apiservice_master-GJCRJX6ZJPDVVSEUHIS6VBX7OYMFS5WKRVRKCSF4PSO76ZGZPKFQ] Running shell script
+ docker build -t eu.gcr.io/xxxxx/apiservice:master.1 .
/var/jenkins_home/workspace/apiservice_master-GJCRJX6ZJPDVVSEUHIS6VBX7OYMFS5WKRVRKCSF4PSO76ZGZPKFQ@tmp/durable-b4503ecc/script.sh: 2: /var/jenkins_home/workspace/apiservice_master-GJCRJX6ZJPDVVSEUHIS6VBX7OYMFS5WKRVRKCSF4PSO76ZGZPKFQ@tmp/durable-b4503ecc/script.sh: docker: not found
``` 

What am I doing wrong? When I ssh into the instance docker is available.

**Comment by viglesiasce** [comment]
Did you setup your pod template config to bind mount the docker socket and docker binary? 

More info here in step 13:
https://cloud.google.com/solutions/configuring-jenkins-container-engine#configuring_the_build_executors

**Comment by s-pk** [comment]
Just to add on here: with a cluster upgrade in GKE I am also having this issue. Nothing has changed other than a cluster upgrade and it is no longer working :/

**Comment by anurag-itsolvs** [comment]
Have any one find solution for this issue?
I am also having this issue.

**Comment by viglesiasce** [comment]
Was Jenkins installed with the instructions from this repo? If not, can you check that your master is set to have 0 build executors?

**Comment by s-pk** [comment]
Finally fixed this. I can briefly describe what happened. We updated our GKE cluster, which in turn updated the underlying COS image. In this update to COS it updated the Docker version which took the Docker binary from a unlinked binary, to being linked to a few things (apparmor, etc). The only way for us to fix this was to install Docker inside of the Docker image itself, but still use the socket from the Kubernetes node. We could not use the Docker binary from the Kubernetes node, or it would fail because it could not find certain dependencies.

I'm not sure if that is still the case, or if it was just a specific version of COS that was causing this to happen.

**Comment by viglesiasce** [comment]
@s-pk this commit fixes the apparmor issue:
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/commit/97d6a15f766abf3bcddb0ab08369916b0fc7dd58

And that image was pushed as gcr.io/cloud-solutions-images/jenkins-slave-image:v4

**Comment by s-pk** [comment]
Ah I see 👍, since we ran into this in June, I had since just used our quick fix by installing Docker in the image. Now that I see you have pushed that, I will switch back. Thanks!

**Comment by khwerhahn** [comment]
Thank you @viglesiasce . It solved it.
