### ISSUE TITLE
Document Jenkins configuration

### ISSUE THREAD

**Issue by joshwand** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#78]
The rather complex setup for using the Kubernetes plugin in Jenkins is hidden away in the preconfigured raw jenkins disk image. If I am using this project as a template/tutorial for how to configure my own Jenkins instance, I have to build this entire project, deploy it to GKE, and manually examine the Jenkins config to see how it's done.

It would be more useful to document the steps required to configure the k8s and google oauth plugins on Jenkins to work in the GKE environment.

**Comment by viglesiasce** [comment]
This has all been codified in the [Helm chart](https://github.com/kubernetes/charts/tree/master/stable/jenkins) as well as the following docs:

https://cloud.google.com/solutions/jenkins-on-container-engine
https://cloud.google.com/solutions/configuring-jenkins-container-engine
