### ISSUE TITLE
Failed Sync

### ISSUE THREAD

**Issue by briantq** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#82]
I am trying to follow the steps in the instructions and am stuck when trying to create the service and pods.  Specifically, when I apply the contents of the k8s directory, the pod never starts.  When I do a describe on the pod, I see "FailedSync" and a message of _Error syncing pod, skipping: failed to "StartContainer" for "master" with CrashLoopBackOff: "Back-off 20s restarting failed container=master pod=jenkins-3366133267-243lz_jenkins(a4b07e8b-4c5d-11e7-836a-42010a8000a5)"_.  

My Kubernetes version is 1.6.4.  I saw after 1.6.0 the apiVersion changed to "apps/v1beta1" with respect to deployments. I tried both the new string and the old one but still got the same error.  Any insight on other things to try to logs that might help determine the issue?

**Comment by JohnAdamsy** [comment]
It could be a number of things. What do you get on `kubectl --namespace=production logs <created-pod-name> -p` ?

**Comment by viglesiasce** [comment]
Still seeing this @briantq?
