### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### ISSUE THREAD

**Issue by manuelcugliari** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#83]
Hi,
    from the pipeline I'am trying to start a docker build, but I get always "Cannot connect to the Docker daemon. Is the docker daemon running on this host?".

Inside the jenkins container the command " ls -la /var/run/docker.sock" gives:
srw-rw----  1 root  450    0 May  9 12:17 docker.sock

Manuel

**Comment by gm42** [comment]
Your user is not in the group `450`; this is also not an issue relevant to this repo?

**Comment by viglesiasce** [comment]
@manuelcugliari are you using the slave image from this repo? If not ensure that your image is running as root otherwise you will get a perm denied when trying to run docker commands.

**Comment by viglesiasce** [comment]
Latest update of the tutorial in #96 uses Container Builder to do the docker builds:

https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/master/sample-app/Jenkinsfile#L53
