### ISSUE TITLE
Pushing a 'production' branch will deploy to the 'production' namespace

### ISSUE THREAD

**Issue by lvdh** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#91]
(... unless I am missing something.)

Granted, this is an edge case. However, it could be fixed with a straightforward and non-intrusive change. Being an example for an actual production setup, I believe this change would be a worthwhile addition.

Initial [suggestion of a fix](https://github.com/lvdh/continuous-deployment-on-kubernetes/blob/lvdh/jenkinsfile-production-case/sample-app/Jenkinsfile#L38-L41).

As per the [contribution guidelines](https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/65f4fd277bb0100205263dc13c08cd5693406f57/CONTRIBUTING.md), I will submit a PR only if the proposed change is accepted.

**Comment by viglesiasce** [comment]
Hey @lvdh that sounds great!!! Lets make it happen.

(Apologies for the delay).

**Comment by lvdh** [comment]
Hi @viglesiasce, PR created; https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/pull/116

Allow me to kindly refuse your apologies, and offer you mine. Apologies for the considerable delay!
